apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-todo-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-todo-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-todo-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-todo-front
        image: kubernetestutorial.azurecr.io/getting-started:0.1
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: azure-todo-front
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 3000
#   selector:
#     app: azure-todo-front